name: CI

on: [push]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Say Hello"
        run: echo "Hello Daniele!" && exit 1
      - name: "Say Foo"
        run: echo "Foo"
